name: Build for Rasberry Pi

on:
  push:
    branches:
      - master

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  DOCKER_IMAGE_NAME: build_for_raspi

jobs:
  build:
    name: Build for Rasberry Pi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ghcr_ACCESS_TOKEN }}

#      - name: Build and Push ARM64 Image
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          file: ./docker/Dockerfile
#          platforms: linux/arm64
#          builder: ${{ steps.buildx.outputs.name }}
#          push: true
#          tags: | 
#            ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:latest
#          cache-from: type=gha
#          cache-to: type=gha,mode=max

      - name: Run for Raspberry Pi Builds
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes  
          docker run --rm --platform linux/arm64 --volume $PWD:/io ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:latest /io/essentia/build_essentia.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: essentia-linux-arm
          path: releases/    
